

WITH HIST AS (
    SELECT 
        H.HISTORY_ID,
        C.CAR_TYPE,
        C.DAILY_FEE,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS D,
        CASE 
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE '7일 미만'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'    
)

SELECT
    H.HISTORY_ID,
    FLOOR(H.D * H.DAILY_FEE * (1 - COALESCE(P.DISCOUNT_RATE, 0) / 100)) AS FEE
FROM HIST H
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON H.CAR_TYPE = P.CAR_TYPE AND H.DURATION_TYPE = P.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC

# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
# JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
# WHERE C.CAR_TYPE = '트럭'
# ORDER BY H.HISTORY_ID