-- 코드를 입력하세요

SELECT A.FLAVOR
FROM (SELECT SUM(TOTAL_ORDER) AS TOTAL_ORDER, FLAVOR FROM FIRST_HALF GROUP BY FLAVOR) AS A
JOIN (SELECT SUM(TOTAL_ORDER) AS TOTAL_ORDER, FLAVOR FROM JULY GROUP BY FLAVOR) AS B
ON A.FLAVOR = B.FLAVOR
ORDER BY (A.TOTAL_ORDER + B.TOTAL_ORDER) DESC
LIMIT 3
