-- 코드를 입력하세요
SELECT 
    AP.APNT_NO, 
    PA.PT_NAME, 
    AP.PT_NO, 
    AP.MCDP_CD, 
    DOC.DR_NAME, 
    AP.APNT_YMD
FROM 
    APPOINTMENT AP
INNER JOIN 
    PATIENT PA ON AP.PT_NO = PA.PT_NO
INNER JOIN 
    DOCTOR DOC ON AP.MDDR_ID = DOC.DR_ID
WHERE 
    DATE(AP.APNT_YMD) = '2022-04-13'
    AND APNT_CNCL_YN = 'N'
    AND AP.MCDP_CD = 'CS'
ORDER BY 
    AP.APNT_YMD ASC

# SELECT * 
# FROM APPOINTMENT
# ORDER BY APNT_YMD