WITH REVIEW_COUNT AS (
    SELECT MEMBER_ID, COUNT(*) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
BEST_REVIEWER AS (
    SELECT MEMBER_ID
    FROM REVIEW_COUNT
    WHERE CNT = (SELECT MAX(CNT) FROM REVIEW_COUNT)
)
SELECT 
    B.MEMBER_NAME, 
    C.REVIEW_TEXT, 
    DATE_FORMAT(C.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM BEST_REVIEWER A
JOIN MEMBER_PROFILE B ON A.MEMBER_ID = B.MEMBER_ID
JOIN REST_REVIEW C ON A.MEMBER_ID = C.MEMBER_ID
ORDER BY C.REVIEW_DATE ASC, C.REVIEW_TEXT ASC;