
SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_TREE T
INNER JOIN ITEM_INFO C
ON T.ITEM_ID = C.ITEM_ID
INNER JOIN ITEM_INFO P
ON T.PARENT_ITEM_ID = P.ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY C.ITEM_ID DESC