-- 코드를 작성해주세요

# SELECT I.ID, N.FISH_NAME, I.LENGTH
SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I
INNER JOIN FISH_NAME_INFO N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE I.LENGTH = (SELECT MAX(L.LENGTH) 
                  FROM FISH_INFO L
                  WHERE L.FISH_TYPE = I.FISH_TYPE)
ORDER BY ID ASC
